#!/bin/sh
cd "${0%/*}" || exit # Run from this directory

#------------------------------------------------------------------------------

# Libraries
wclean -all src

# Applications
wclean -all applications

#------------------------------------------------------------------------------
