#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

(
    cd depInitialState || exit

    # runApplication blockMesh  # TODO: replace with correct mesh generation command
    # maybe add the renumber command

    runApplication decomposePar
    runParallel $(getApplication)
    runApplication reconstructPar -latestTime
    rm -f log.reconstructPar
)

(
    cd depSeparation || exit

    # Overwrite 0/ with the contents of 0.orig/ if it exists.
    # The -processor option to do the processor directories instead
    restore0Dir

    # runApplication blockMesh

    runApplication mapFields ../depInitialState -sourceTime latestTime
    runApplication decomposePar
    runParallel $(getApplication)
    runApplication reconstructPar
)

#------------------------------------------------------------------------------
