#!/usr/bin/env bash
cd "${0%/*}" || exit # Run from this directory
. ${WM_PROJECT_DIR:?}/wmake/scripts/AllwmakeParseArguments

#------------------------------------------------------------------------------

lagrangian/Allwmake $targetType $*

#------------------------------------------------------------------------------
